[package]
name = "favicon"
version = "0.2.0"
edition = "2021"
authors = ["Leonard Woo <leo_916@yahoo.com>"]
license = "BSD 3-Clause License"
description = "A CLI tool for convert favicon"
readme = "README.adoc"
keywords = ["cli", "favicon"]
categories = ["command-line-utilities"]
homepage = "https://github.com/leonardwoo/favicon"
build = "build.rs"
publish = false

[[bin]]
name = "favicon"
path = "src/main.rs"
bench = false

[dependencies]
image = "*"
futures = "0.3"

[package.metadata.winres]
FileDescription = "Favicon"
LegalCopyright = "Copyright © Leonard Woo"
OriginalFilename = "favicon.exe"
ProductName = "Favicon"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
